sed -i -e 's/\r$/\n/' about.sh
sed -i -e 's/\r$/\n/' add-host.sh
sed -i -e 's/\r$/\n/' add-l2tp.sh
sed -i -e 's/\r$/\n/' add-pptp.sh
sed -i -e 's/\r$/\n/' add-ss.sh
sed -i -e 's/\r$/\n/' add-ssr.sh
sed -i -e 's/\r$/\n/' add-sstp.sh
sed -i -e 's/\r$/\n/' add-tr.sh
sed -i -e 's/\r$/\n/' add-vless.sh
sed -i -e 's/\r$/\n/' add-wg.sh
sed -i -e 's/\r$/\n/' add-ws.sh
sed -i -e 's/\r$/\n/' autobackup.sh
sed -i -e 's/\r$/\n/' autokill.sh
sed -i -e 's/\r$/\n/' backup.sh
sed -i -e 's/\r$/\n/' bbr.sh
sed -i -e 's/\r$/\n/' bckp.sh
sed -i -e 's/\r$/\n/' cek-pptp.sh
sed -i -e 's/\r$/\n/' cek-ss.sh
sed -i -e 's/\r$/\n/' cek-sstp.sh
sed -i -e 's/\r$/\n/' cek-tr.sh
sed -i -e 's/\r$/\n/' cek-vless.sh
sed -i -e 's/\r$/\n/' cek-wg.sh
sed -i -e 's/\r$/\n/' cek-ws.sh
sed -i -e 's/\r$/\n/' cek.sh
sed -i -e 's/\r$/\n/' ceklim.sh
sed -i -e 's/\r$/\n/' cert.sh
sed -i -e 's/\r$/\n/' cf.sh
sed -i -e 's/\r$/\n/' change.sh
sed -i -e 's/\r$/\n/' clear-log.sh
sed -i -e 's/\r$/\n/' del-l2tp.sh
sed -i -e 's/\r$/\n/' del-pptp.sh
sed -i -e 's/\r$/\n/' del-ss.sh
sed -i -e 's/\r$/\n/' del-ssr.sh
sed -i -e 's/\r$/\n/' del-sstp.sh
sed -i -e 's/\r$/\n/' del-tr.sh
sed -i -e 's/\r$/\n/' del-vless.sh
sed -i -e 's/\r$/\n/' del-wg.sh
sed -i -e 's/\r$/\n/' del-ws.sh
sed -i -e 's/\r$/\n/' delete.sh
sed -i -e 's/\r$/\n/' edu.sh
sed -i -e 's/\r$/\n/' go.sh
sed -i -e 's/\r$/\n/' hapus.sh
sed -i -e 's/\r$/\n/' info.sh
sed -i -e 's/\r$/\n/' ins-vt.sh
sed -i -e 's/\r$/\n/' ipsec.sh
sed -i -e 's/\r$/\n/' limit-speed.sh
sed -i -e 's/\r$/\n/' member.sh
sed -i -e 's/\r$/\n/' menuu.sh
sed -i -e 's/\r$/\n/' menu.sh
sed -i -e 's/\r$/\n/' port-ovpn.sh
sed -i -e 's/\r$/\n/' port-squid.sh
sed -i -e 's/\r$/\n/' port-ssl.sh
sed -i -e 's/\r$/\n/' port-sstp.sh
sed -i -e 's/\r$/\n/' port-tr.sh
sed -i -e 's/\r$/\n/' port-vless.sh
sed -i -e 's/\r$/\n/' port-wg.sh
sed -i -e 's/\r$/\n/' port-ws.sh
sed -i -e 's/\r$/\n/' renew-l2tp.sh
sed -i -e 's/\r$/\n/' renew-pptp.sh
sed -i -e 's/\r$/\n/' renew-ss.sh
sed -i -e 's/\r$/\n/' renew-ssr.sh
sed -i -e 's/\r$/\n/' renew-sstp.sh
sed -i -e 's/\r$/\n/' renew-tr.sh
sed -i -e 's/\r$/\n/' renew-vless.sh
sed -i -e 's/\r$/\n/' renew-wg.sh
sed -i -e 's/\r$/\n/' renew-ws.sh
sed -i -e 's/\r$/\n/' ram.sh
sed -i -e 's/\r$/\n/' renew.sh
sed -i -e 's/\r$/\n/' restart.sh
sed -i -e 's/\r$/\n/' restore.sh
sed -i -e 's/\r$/\n/' scvpn.sh
sed -i -e 's/\r$/\n/' set-br.sh
sed -i -e 's/\r$/\n/' setup.sh
sed -i -e 's/\r$/\n/' sodosok.sh
sed -i -e 's/\r$/\n/' ssh-vpn.sh
sed -i -e 's/\r$/\n/' ssr.sh
sed -i -e 's/\r$/\n/' ssrmu.sh
sed -i -e 's/\r$/\n/' sstp.sh
sed -i -e 's/\r$/\n/' strt.sh
sed -i -e 's/\r$/\n/' swapkvm.sh
sed -i -e 's/\r$/\n/' tendang.sh
sed -i -e 's/\r$/\n/' trial.sh
sed -i -e 's/\r$/\n/' update-1.2.sh
sed -i -e 's/\r$/\n/' usernew.sh
sed -i -e 's/\r$/\n/' vpn.sh
sed -i -e 's/\r$/\n/' welcomeadmin.sh
sed -i -e 's/\r$/\n/' wg.sh
sed -i -e 's/\r$/\n/' xp.sh