shc -r -f /root/enc/about.sh -o about.sh
shc -r -f /root/enc/add-host.sh -o add-host.sh
shc -r -f /root/enc/add-l2tp.sh -o add-l2tp.sh
shc -r -f /root/enc/add-pptp.sh -o add-pptp.sh
shc -r -f /root/enc/add-ss.sh -o add-ss.sh
shc -r -f /root/enc/add-ssr.sh -o add-ssr.sh
shc -r -f /root/enc/add-sstp.sh -o add-sstp.sh
shc -r -f /root/enc/add-tr.sh -o add-tr.sh
shc -r -f /root/enc/add-vless.sh -o add-vless.sh
shc -r -f /root/enc/add-ws.sh -o add-ws.sh
shc -r -f /root/enc/add-wg.sh -o add-wg.sh
shc -r -f /root/enc/edu.sh -o edu.sh
shc -r -f /root/enc/autobackup.sh -o autobackup.sh
shc -r -f /root/enc/autokill.sh -o autokill.sh
shc -r -f /root/enc/backup.sh -o backup.sh
shc -r -f /root/enc/bckp.sh -o bckp.sh
shc -r -f /root/enc/cek-l2tp.sh -o cek-l2tp.sh
shc -r -f /root/enc/cek-pptp.sh -o cek-pptp.sh
shc -r -f /root/enc/cek-ss.sh -o cek-ss.sh
shc -r -f /root/enc/cek-sstp.sh -o cek-sstp.sh
shc -r -f /root/enc/cek-tr.sh -o cek-tr.sh
shc -r -f /root/enc/cek-vless.sh -o cek-vless.sh
shc -r -f /root/enc/cek-ws.sh -o cek-ws.sh
shc -r -f /root/enc/cek-wg.sh -o cek-wg.sh
shc -r -f /root/enc/cf.sh -o cf.sh
shc -r -f /root/enc/change.sh -o change.sh
shc -r -f /root/enc/del-l2tp.sh -o del-l2tp.sh
shc -r -f /root/enc/del-pptp.sh -o del-pptp.sh
shc -r -f /root/enc/del-ss.sh -o del-ss.sh
shc -r -f /root/enc/del-ssr.sh -o del-ssr.sh
shc -r -f /root/enc/del-sstp.sh -o del-sstp.sh
shc -r -f /root/enc/del-tr.sh -o del-tr.sh
shc -r -f /root/enc/del-vless.sh -o del-vless.sh
shc -r -f /root/enc/del-ws.sh -o del-ws.sh
shc -r -f /root/enc/del-wg.sh -o del-wg.sh
shc -r -f /root/enc/info.sh -o info.sh
shc -r -f /root/enc/ins-vt.sh -o ins-vt.sh
shc -r -f /root/enc/ipsec.sh -o ipsec.sh
shc -r -f /root/enc/limit-speed.sh -o limit-speed.sh
shc -r -f /root/enc/menuu.sh -o menuu.sh
shc -r -f /root/enc/port-ovpn.sh -o port-ovpn.sh
shc -r -f /root/enc/port-squid.sh -o port-squid.sh
shc -r -f /root/enc/port-ssl.sh -o port-ssl.sh
shc -r -f /root/enc/port-sstp.sh -o port-sstp.sh
shc -r -f /root/enc/port-tr.sh -o port-tr.sh
shc -r -f /root/enc/port-vless.sh -o port-vless.sh
shc -r -f /root/enc/port-ws.sh -o port-ws.sh
shc -r -f /root/enc/port-wg.sh -o port-wg.sh
shc -r -f /root/enc/renew-l2tp.sh -o renew-l2tp.sh
shc -r -f /root/enc/renew-pptp.sh -o renew-pptp.sh
shc -r -f /root/enc/renew-ss.sh -o renew-ss.sh
shc -r -f /root/enc/renew-ssr.sh -o renew-ssr.sh
shc -r -f /root/enc/renew-sstp.sh -o renew-sstp.sh
shc -r -f /root/enc/renew-tr.sh -o renew-tr.sh
shc -r -f /root/enc/renew-vless.sh -o renew-vless.sh
shc -r -f /root/enc/renew-ws.sh -o renew-ws.sh
shc -r -f /root/enc/renew-wg.sh -o renew-wg.sh
shc -r -f /root/enc/restart.sh -o restart.sh
shc -r -f /root/enc/restore.sh -o restore.sh
shc -r -f /root/enc/set-br.sh -o set-br.sh
shc -r -f /root/enc/setup.sh -o setup.sh
shc -r -f /root/enc/sodosok.sh -o sodosok.sh
shc -r -f /root/enc/ssh-vpn.sh -o ssh-vpn.sh
shc -r -f /root/enc/ssr.sh -o ssr.sh
shc -r -f /root/enc/ssrmu.sh -o ssrmu.sh
shc -r -f /root/enc/sstp.sh -o sstp.sh
shc -r -f /root/enc/strt.sh -o strt.sh
shc -r -f /root/enc/swapkvm.sh -o swapkvm.sh
shc -r -f /root/enc/tendang.sh -o tendang.sh
shc -r -f /root/enc/trial.sh -o trial.sh
shc -r -f /root/enc/usernew.sh -o usernew.sh
shc -r -f /root/enc/vpn.sh -o vpn.sh
shc -r -f /root/enc/webmin.sh -o webmin.sh
shc -r -f /root/enc/welcomeadmin.sh -o welcomeadmin.sh
shc -r -f /root/enc/wg.sh -o wg.sh
shc -r -f /root/enc/xp.sh -o xp.sh
shc -r -f /root/enc/bbr.sh -o bbr.sh