shc -r -f about.sh -o about.sh
shc -r -f add-host.sh -o add-host.sh
shc -r -f add-l2tp.sh -o add-l2tp.sh
shc -r -f add-pptp.sh -o add-pptp.sh
shc -r -f add-ss.sh -o add-ss.sh
shc -r -f add-ssr.sh -o add-ssr.sh
shc -r -f add-sstp.sh -o add-sstp.sh
shc -r -f add-tr.sh -o add-tr.sh
shc -r -f add-vless.sh -o add-vless.sh
shc -r -f add-ws.sh -o add-ws.sh
shc -r -f add-wg.sh -o add-wg.sh
shc -r -f edu.sh -o edu.sh
shc -r -f autobackup.sh -o autobackup.sh
shc -r -f autokill.sh -o autokill.sh
shc -r -f backup.sh -o backup.sh
shc -r -f bckp.sh -o bckp.sh
shc -r -f cek-l2tp.sh -o cek-l2tp.sh
shc -r -f cek-pptp.sh -o cek-pptp.sh
shc -r -f cek-ss.sh -o cek-ss.sh
shc -r -f cek-sstp.sh -o cek-sstp.sh
shc -r -f cek-tr.sh -o cek-tr.sh
shc -r -f cek-vless.sh -o cek-vless.sh
shc -r -f cek-ws.sh -o cek-ws.sh
shc -r -f cek-wg.sh -o cek-wg.sh
shc -r -f cf.sh -o cf.sh
shc -r -f change.sh -o change.sh
shc -r -f del-l2tp.sh -o del-l2tp.sh
shc -r -f del-pptp.sh -o del-pptp.sh
shc -r -f del-ss.sh -o del-ss.sh
shc -r -f del-ssr.sh -o del-ssr.sh
shc -r -f del-sstp.sh -o del-sstp.sh
shc -r -f del-tr.sh -o del-tr.sh
shc -r -f del-vless.sh -o del-vless.sh
shc -r -f del-ws.sh -o del-ws.sh
shc -r -f del-wg.sh -o del-wg.sh
shc -r -f info.sh -o info.sh
shc -r -f ins-vt.sh -o ins-vt.sh
shc -r -f ipsec.sh -o ipsec.sh
shc -r -f limit-speed.sh -o limit-speed.sh
shc -r -f menuu.sh -o menuu.sh
shc -r -f port-ovpn.sh -o port-ovpn.sh
shc -r -f port-squid.sh -o port-squid.sh
shc -r -f port-ssl.sh -o port-ssl.sh
shc -r -f port-sstp.sh -o port-sstp.sh
shc -r -f port-tr.sh -o port-tr.sh
shc -r -f port-vless.sh -o port-vless.sh
shc -r -f port-ws.sh -o port-ws.sh
shc -r -f port-wg.sh -o port-wg.sh
shc -r -f renew-l2tp.sh -o renew-l2tp.sh
shc -r -f renew-pptp.sh -o renew-pptp.sh
shc -r -f renew-ss.sh -o renew-ss.sh
shc -r -f renew-ssr.sh -o renew-ssr.sh
shc -r -f renew-sstp.sh -o renew-sstp.sh
shc -r -f renew-tr.sh -o renew-tr.sh
shc -r -f renew-vless.sh -o renew-vless.sh
shc -r -f renew-ws.sh -o renew-ws.sh
shc -r -f renew-wg.sh -o renew-wg.sh
shc -r -f restart.sh -o restart.sh
shc -r -f restore.sh -o restore.sh
shc -r -f set-br.sh -o set-br.sh
shc -r -f setup.sh -o setup.sh
shc -r -f sodosok.sh -o sodosok.sh
shc -r -f ssh-vpn.sh -o ssh-vpn.sh
shc -r -f ssr.sh -o ssr.sh
shc -r -f ssrmu.sh -o ssrmu.sh
shc -r -f sstp.sh -o sstp.sh
shc -r -f strt.sh -o strt.sh
shc -r -f swapkvm.sh -o swapkvm.sh
shc -r -f tendang.sh -o tendang.sh
shc -r -f trial.sh -o trial.sh
shc -r -f usernew.sh -o usernew.sh
shc -r -f vpn.sh -o vpn.sh
shc -r -f webmin.sh -o webmin.sh
shc -r -f welcomeadmin.sh -o welcomeadmin.sh
shc -r -f wg.sh -o wg.sh
shc -r -f xp.sh -o xp.sh